name: scansol2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.4.10
  barcode: ^2.2.6
  google_fonts: ^6.1.0

  image_cropper: 8.0.2
  # QR 및 PDF 관련 (필수)
  pdf: ^3.10.0
  printing: ^5.11.0
  http: ^1.1.0

  # 기타 사용 중인 패키지
  cupertino_icons: ^1.0.8
  mobile_scanner: ^7.1.4
  qr_flutter: ^4.1.0
  shared_preferences: 2.3.2
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  path: ^1.9.1
  firebase_auth: ^5.7.0
  flutter_secure_storage: ^9.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  # 구글 폰트를 에셋으로 직접 다운로드하여 사용하는 경우 아래 설정을 추가합니다.
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.ttf
        - asset: assets/fonts/NotoSansKR-Bold.ttf
          weight: 700

  # [중요] 이미지가 있는 폴더 경로를 정확히 지정
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 23